@startuml
skinparam classAttributeIconSize 0
'抽象主题
Abstract Subject{
    # observers : List<Observer>
    + add(Observer observer) : void
    + remove(Observer observer) : void
    + notifyObserver() : void
}

'具体主题
Class ConcreteSubject{
    + notifyObserver() : void
}
ConcreteSubject--|> Subject
'抽象观察者
Abstract Observer{
    + response(): void
}
Observer --o Subject
'具体观察者
Class ConcreteObserverA{
       + response(): void
}
Class ConcreteObserverB{
       + response(): void
}
ConcreteObserverA --|> Observer
ConcreteObserverB --|> Observer

Class Client
Client ..>Observer
Client ..> Subject
@enduml